### ISSUE TITLE
Allow attaching shared networks to firewalls

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-api#102]
It is in some cases required to be able to enable machines from multiple projects have direct access through the firewall to special purpose networks like storage.

The proposed solution is to mark a private machine network as a shared network, which allows all other consumers to attach to this network as well.

/cc @mwennrich @muhittink @Gerrit91

**Comment by mwindower** [comment]
There are different ways to solve this issue.

**1. Using a dedicated network for storage nodes**

Pro
- making storage nodes accessible for clusters is straight forwards 

Contra
- is somehow comparable to a private network but needs manual "allocation" of the prefix and VRF
- machines have no private network at all => validations and ASN determination in the metal-api have to be modified

**2. Using a standard private network without project reference**

Clusters that want storage access would have two private networks
- their "primary" private network for worker IPs
- and the private network for communication with the storage nodes (which has no project reference)

Pro
- is a real private network: prefix, VRF and ASN come without any changes

Contra
- constraints for network allocation have to be weakened
- machine allocation has to differentiate btw. the primary private network and secondary private networks (those without project reference)

After looking into the code the second approach is my favorite one.

WDYT?

**Comment by majst01** [comment]
But howto allocate a "secondary" private network

**Comment by mwindower** [comment]
For the storage nodes we could allocate a private network without project id.
During firewall creation of k8s clusters this network is allowed to be in the list of "additional networks".

**Comment by majst01** [comment]
This way we can modify the creation of the current storage network to have set `private: true` and try again !

**Comment by majst01** [comment]
no we cant, private network is evaluated by looking at a privatesuper given
