### ISSUE TITLE
Garbage collection of orphaned machines

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-api#116]
If machines are not able to report back to metal-api because they are not there anymore, or dead for other unknown reasons, we should think about implementing a gc for these types of machines.

The gc-algorithm should check for the timestamp of the last machine update and remove the entity after a configurable amount of time (5day for example).

**Comment by majst01** [comment]
The downside of a garbage collection is that we loose broken machine visibility.
We should instead add a `metalctl machine remove-broken` which is executed by a OPS person which has changed the dead machine and will remove the broken machine with a replacement.

**Comment by muhittink** [comment]
It's quite difficult to do this automatically. A malfunctioned machine will not report back, maybe for weeks. It would be cool if an admin could manage this manually with an api call with metalctl.

**Comment by muhittink** [comment]
Done with #154
