### ISSUE TITLE
Review machine labels

### ISSUE THREAD

**Issue by mwindower** [metal-stack/metal-api#120]
Currently we attach all labels from all networks of an allocation to a machine.

Which of them do we really need? Perhaps we can remove all/most of those labels?

**Comment by Gerrit91** [comment]
Yes, in my opinion the network labels should be removed. I cannot think of a good use-case for that. Over time we introduced some common network labels, which are now being added to machines, like `network.metal-stack.io/default-external=` and `network.metal-stack.io/default=`. I think this is just misleading information.
