### ISSUE TITLE
Possibility to delete orphaned/repaired machines from the api/database

### ISSUE THREAD

**Issue by muhittink** [metal-stack/metal-api#153]
Sometimes it is necessary to remove a repaired machine from the api/database. The UUID will change when a mainboard or a machine is replaced by the vendor. An admin needs the possibility to remove this orphaned machine from the API because the old UUID will be never registered again, something like:

`metalctl machine remove/repair bbbe3200-6a76-11e9-8000-ac1f6b7bece4`

For safety reasons, this should be not possible with a "phoned home" machine without issues.

**Comment by Gerrit91** [comment]
As the `rm machine` command is already used by metalctl, we could also introduce another flag for this new functionality, which could look something like:

```
metalctl machine rm   bbbe3200-6a76-11e9-8000-ac1f6b7bece4 --remove-from-database --yes-i-really-mean-it
```
