### ISSUE TITLE
Firmware upload restricted by HMAC lifetime

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-api#177]
When set too short, the HMAC lifetime will prevent the firmware upload, which makes the firmware upload endpoint dependent on the user's internet connection speed.

**Comment by majst01** [comment]
Should be solved once we replaced HMAC with fine grained permissions

**Comment by Gerrit91** [comment]
Closing because in the long run we want to get rid off HMAC auth and the firmware feature is pretty much unimportant at the moment anyway (needs re-implementation).
