### ISSUE TITLE
machine already allocated

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-api#19]
```
  a18357ac-dba2-11e9-9e70-8ebea97dd3a9  chbtest         1.14.3   nbg-w8101-seed  chbtest.p8hhh9.cluster.metal-pod.io         Processing  89% [Create]      True       False    True   True    26m 51s  
```

```
  lasterror:
    description: 'Flow "Shoot cluster reconciliation" encountered task errors: [task
      "Waiting until shoot worker nodes have been reconciled" failed: Error while
      waiting for worker object to become ready: retry failed with context deadline
      exceeded, last error: extension encountered error during reconciliation: Error
      reconciling worker: Failed while waiting for all machine deployments to be ready:
      ''Machine shoot--p8hhh9--chbtest-default-worker-z1-f597984-7dmpk failed: Cloud
      provider message - Post https://api.metal-pod.io/metal/v1/machine/allocate:
      machine "00000000-beef-beef-0010-efbeaddeefbe" already allocated'']'
```

This actually happens if there were two requests in parallel trying to allocate the same machine. One gets through, the other one fails with this message.

I guess, the machine-controller-manager triggers the allocation calls for multiple nodes in parallel, then we fetch the same machine out of the wait table... one request gets through, the other one fails.

We could try to mitigate this by fetching a random machine from the wait table and not just the first entry of the search query result?

**Comment by Gerrit91** [comment]
Picking the random machine was added.

**Comment by majst01** [comment]
I would close this issues as this did not happen since #8 was merged anymore.

**Comment by Gerrit91** [comment]
It only does not happen anymore as soon as there are enough machines in the free pool, such that there is a only a small chance of allocating the same machine. But probability increases the less machines you have in a partition. An actual solution would somehow need synchronization or retry-logic.

**Comment by majst01** [comment]
So should we reopen and suggest retry-go ?

**Comment by majst01** [comment]
also did not happen anymore thanks #47
