### ISSUE TITLE
On allocation error, machine's preallocation flag is not reset

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-api#195]
For example, when something like this happens:

```
m machine create --name=ms_srv --hostname=ms_host --partition=fra-equ01 --project=6a8a59ff-f3d2-4958-b765-051d3f06e01b --image=debian-10.0.20210519 --networks=78da360b-c4ea-4685-9cf6-26469ec384f1 --size=s1-large-broken-x86
using SSH identity: /home/ms/.ssh/id_ed25519. Another identity can be specified with --sshidentity/-p
Error: machine create error:[POST /v1/machine/allocate][422] allocateMachine default  device:/dev/nvme1n1 does not exist on given hardware (422)
```

The `preallocation` field of the machine in the database is set to `true` and the machine is lost. The problem seems to be that on the rollback we do not call `freeMachine` but only rollback the networks and IP adresses that we created. :/

**Comment by majst01** [comment]
This error is raised here: https://github.com/metal-stack/metal-api/blob/master/cmd/metal-api/internal/service/machine-service.go#L1076 and rollback is triggered in case of an error, dunno understand why the preallocation persists.

**Comment by Gerrit91** [comment]
As I said, we don't call `freeMachine` but only release networks.
