### ISSUE TITLE
Introduce state machine to track machine provisioning sequence

### ISSUE THREAD

**Issue by iljarotar** [metal-stack/metal-api#264]
As mentioned in #166 and #167 there are some problems that can occur during machine provisioning, that are not yet being reported to the user, because handling all the potential scenarios would lead to a complex logic.
A state machine might be a good solution for this, as it can individually react to any sequence of events while still being easy to understand and extend.

**Comment by Gerrit91** [comment]
References #166, #167.

**Comment by majst01** [comment]
FSM ?
