### ISSUE TITLE
Add connection to headscale

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [metal-stack/metal-api#298]
`metal-api` should be able to connect to `headscale` server. For that it should be able to accept `headscale-addr` flag.

cc @majst01 @Gerrit91
In case `headscale` address  is provided `metal-api` will be adding VPN for all projects. But what if `headscale` server will go down for some reason? IMO, it should fail to create new firewalls/machine in that case with explicit error that `headscale` server is down. What do you think?

**Comment by majst01** [comment]
Yes if headscale server is configured but down, machine/firewall creation must fail

**Comment by Gerrit91** [comment]
Yep, please make it conditional --> if headscale server is configured it fails, if it's not configured everything works as before
