### ISSUE TITLE
Headscale is renaming Machine into Node

### ISSUE THREAD

**Issue by juanfont** [metal-stack/metal-api#468]
Hi there,

Headscale maintainer here :)

FYI, we are renaming Machine into Node - to better fit the internal naming of Tailscale. This might impact this project.

You can track the status of the change here https://github.com/juanfont/headscale/pull/1553

Calls like this one might be impacted https://github.com/metal-stack/metal-api/blob/master/cmd/metal-api/internal/service/async-actor.go#L53. In this example you just need s/Machine/Node.

**Comment by Gerrit91** [comment]
Hey Juan! Thanks for raising this issue! We saw you on FOSDEM and really appreciate your work on headscale! 😄

We will consider the changes in our next dependency updates.

**Comment by juanfont** [comment]
Hi :)

v0.23.0 is out!

**Comment by majst01** [comment]
> Hi :)
> 
> v0.23.0 is out!

Will update our infra and this repo soon !

**Comment by Gerrit91** [comment]
Amazing. We've been waiting for this day to come! :D
