### ISSUE TITLE
Missing rollback of IP addresses when allocation goes wrong

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-api#56]
Lately, we encountered a project in which Gardener allocated over 2000 IP addresses over a couple of days just by allocating firewalls and machines. Even though the reason for this is not fully clear, we have obvious parts in the code where we can leak ip addresses.

For example when allocating a machine we run the `makeNetworks` function, which acquires networks and IP addresses for a machine. When something fails after that or even in between, we leaked some IPs because we do not roll back the allocated IPs and networks properly. I think, we always dreamed of implementing a "network garbage collector" that is regularly cleaning up orphaned IP addresses and network entities. 

Probably we should do something...

**Comment by majst01** [comment]
We must enforce our project quotas in this respect on the metal-api side and set sensible defaults for ip quotas

**Comment by Gerrit91** [comment]
This was mainly resolved by https://github.com/metal-stack/metal-api/pull/78... network garbage collection would still be nice, but it's much less likely to be needed now. I close it.

**Comment by majst01** [comment]
But still, quota enforcement must be implemented to prevent resource exhausting for whatever reason, make a separate issue
