### ISSUE TITLE
Get rid of NSQ

### ISSUE THREAD

**Issue by kolsa** [metal-stack/metal-api#67]
We already narrowed down the usage of NSQ by removing the `SwitchTopic`, thus only the `MachineTopic` and `AllocationTopic` (introduced by the *alloc-grpc* branch) are still there.  
The latter one is used by publishers and consumers that belong only to `metal-api` (whenever a machine is allocated, they are used to pick-up the api instance that holds the gRPC stream to the targeted machine).

As a first improvement, if we can replace the `MachineTopic` with something better or at least make it api-intern too, we would be able to make NSQ private within the control plane, which simplifies our NSQ configuration in that we do not need to use TLS. It also addresses the issue with our publicly accessible nsqlookpd instances.

Currently `metal-api` uses `MachineTopic` to instruct `metal-core` to do the following machine related tasks:
1. power on machine
1. power off machine
1. power reset machine
1. boot machine into BIOS
1. reinstall machine
1. power on chassis identify LED
1. power off chassis identify LED

NSQ then addresses only those core instances that are responsible for the partition containing the targeted machine (condition **C**).

In essence, `metal-api` publishes to and `metal-core` consumes from the `MachineTopic`.  

It would be feasible and also reasonable (more on this shortly) to replace this event mechanism with gRPC uni-directional streams and some additional work (more on this later).

All core instances open a gRPC stream to `metal-api` right after start-up and keep listen to it.  
Whenever such a machine instruction needs to be processed, `metal-api` simply informs *all* core instances via the gRPC streams by additionally providing the targeted partition ID. All core instances that do not belong to that partition simply ignore the machine instruction, which satisfies condition **C**.

As a result, we would get two gRPC streams per partition, which should not be a problem regarding performance. But there are three issues with this approach:

1. `metal-core` needs to take care of the gRPC stream, i.e. it has to reopen the connection whenever it fails, e.g. due to a `metal-api` update or restart. We can solve this by spawning the gRPC stream within a Go routine endlessly as we already do with the wait-for-allocation streams.

1. The suggested gRPC streams are served by only one of the (currently) three api instances. There is a great chance that machine instructions are not handed off to the right gRPC streams.

1. If the right core instances are down, the machine instruction is lost, since there is no caching or retry mechanism (and we do not want to invent one).

The current implementation solves the last two issues with the nature of NSQ, since the machine instruction is broadcasted to all `metal-core` consumers. Even if the right ones are down, the instruction remains in the corresponding channels until the broken core instances are up again and eventually consume it.  

Thus we would be better off reusing this mechanism, but rather than consuming from `metal-core`, we consume right from `metal-api` (such as with `AllocationTopic`) and therewith allowing to make NSQ private.

But this then only solves the second issue, because the machine instruction will be lost if the responsible core instances are down, i.e. each api instance consumes the instruction, writes it to all its open gRPC streams and then forgets about it. Since the responsible core instances are down, they effectively get missed.  
Even if the core instances would respond to the api instances whether they successfully handled the instruction or not (which is a requirement for this approach), without any special caching mechanism (we still do not want to do this here) they could only requeue the instruction, which would result in more and more identical queued instructions over time and therewith endless re-executions.

So let's take a step back.

If we implement this approach so far (gRPC streams + private NSQ), the question arises which role does NSQ still play.
We would have two private topics, `MachineTopic` and `AllocationTopic`, which are used by *one* api instance to inform the other ones (and also itself) about a task, which eventually will be executed by *all* api instances as soon as they consume them from these topics.  
Hence, we still need the NSQ broadcast feature, but not its caching feature, since we've seen that it doesn't help us with the third issue.

NSQ is rather heavyweight regarding our requirements, especially if we take the deployment into account (nsqd/nsqlookupd http/tcp addresses, broadcast address, secrets, certs, TLS, ...).  
Wouldn't it be much nicer to get rid of NSQ entirely? All we need is a more lightweight mechanism that (**A**) informs all api instances about a machine instruction, be it the listed machine tasks or the machine allocation task, and (**B**) solves our outstanding third issue with broken core instances by caching the instruction somehow (this is already solved for the machine allocation task, since `metal-core` is not affected at all).

We didn't take ´metalctl´ into account yet, which is the component that triggers all tasks we already talked about. So one possible solution for **A** would be not to loadbalance the trigger but rather broadcast it to all api instances, but this is not provided by k8s out-of-the-box and it doesn't solve **B** either.

So let's keep that untouched and combine **A** and **B** to only one issue **P**, i.e. how can a single api instance reliably pass-through a machine instruction to the responsible core instances?
 
Ideally the instruction is executed only by one of the two responsible core instances (**P'**), which would be an improvement over the current implementation.

#### Approach to solve both, **P** and **P'**

As soon as the loadbalanced api instance is charged by `metalctl` to hand-off a machine instruction to a certain core instance, it stores the machine instruction in a new `instructions` DB table. In particular, the targeted partition ID, the targeted machine ID, the instruction itself (string) and possible machine instruction arguments (string array).

All api instances get notified by that table whenever an instruction is added and simply forward it into their open gRPC streams, one after another. As soon as a core instance responds success, the affected api instance removes the instruction entry from the table and stops forwarding to its remaining streams. The table should also be polled periodically for unprocessed instructions, though this period can be rather long to reduce DB overhead.

To ensure **P'** it would be also necessary for each api instance to introduce some table locking mechanism, since two related core instances might be connected to distinct api instances. This approach does not suggest a strategy for this.

@majst01 @ulrichSchreiner @Gerrit91 @droid42  @mwindower :
What do you think? Do I miss something or are there any new issues with this approach?

**Comment by kolsa** [comment]
We could also consider to deploy a gRPC sync server into the control-plane, which coordinates tasks that should be handled by all metal-api instances. For this, each metal-api instance keeps a bi-directional gRPC stream to this service and informs it about any task it is considered to do. The service simply broadcasts that task then to all metal-api instances.  
This could avoid synchronization via DB.

**Comment by Gerrit91** [comment]
Hm. The thing that I am a little afraid of is the amount of effort that we have to put into this until we found all the bugs of this entirely new approach. In general, I do not have anything against such fundamental changes, but there is another MEP which could come up soon which is about putting kubelets on the leafs. In case this proposal gets through approval, we would the

**Comment by Gerrit91** [comment]
ha

**Comment by Gerrit91** [comment]
Sorry for closing and re-opening... I struggled with my track pad.

**Comment by majst01** [comment]
As we introduced more dependencies to nsq i am eager to close this issue, it still exists for later reference though.
