### ISSUE TITLE
Provide Mechanism for Database Migration

### ISSUE THREAD

**Issue by Gerrit91** [metal-stack/metal-api#69]
We will come into situations where we need to migrate our database in order to support upgrades from older versions.

The solution should be simple and stable.

**Comment by Gerrit91** [comment]
The mechanism should be part of the "init-db" command, which we use in our deployments anyway before we rollout a new update. 

A solution where you can define the migrations directly in Go would be preferable, I guess. Something simple like this but for RethinkDB would be nice:

https://github.com/go-pg/migrations

**Comment by majst01** [comment]
in masterdata-api we already use: 

github.com/lopezator/migrator

**Comment by Gerrit91** [comment]
Also looking good but there does not seem to be a tool for rethinkdb which does the same kind of thing. Except for this project https://github.com/Coccodrillo/rethinkdb-migrate, which does not seem to be very active anymore...

**Comment by majst01** [comment]
this is a dead project, maybe we could add rethinkdb support to the migrator i mentioned, i would really try to avoid using multiple mechanisms, especially because we use pg from metal-api as well.
